# .github/workflows/backend.yml
name: Deploy Backend to Cloud Run
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: asia-southeast1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
jobs:
  deploy:
    name: Deploy Backend to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: $SA_KEY_JSON
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: $PROJECT_ID

      - name: Copy Dockerfile
        run: cp back-end/Dockerfile Dockerfile

      - name: Build Backend Image
        run: gcloud builds submit --tag $RUN_REGION-docker.pkg.dev/$PROJECT_ID/solar-savings/backend-image:$GITHUB_SHA

      - name: Remove Backend Dockerfile
        run: rm Dockerfile

      - name: Deploy Backend
        run: |
          gcloud run deploy backend \
            --image=$RUN_REGION-docker.pkg.dev/$PROJECT_ID/solar-savings/backend-image:$GITHUB_SHA \
            --region=$RUN_REGION \
            --allow-unauthenticated \
            --set-env-vars="GOOGLE_API_KEY=$GOOGLE_API_KEY" 